apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-rest
  template:
    metadata:
      labels:
        app: node-rest
    spec:
      containers:
      - name: node-container
        image: sandeephub/node-image:1
        ports:
        - containerPort: 3010
          name: http
          protocol: TCP
    - envFrom:
      - configMapRef:
        name: app-settings
      - secretRef:
        name: app-secrets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-db
  labels:
    app: node-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-rest-db
  template:
    metadata:
      labels:
        app: node-rest-db
    spec:
      containers:
      - name: node-container-db
        image: mysql:latest
        ports:
        - containerPort: 3011
          name: http
          protocol: TCP

